import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { DisableDraftMode } from "@/components/molecules/presentation/disableDraftMode";
import { HeaderWrapper } from "@/components/organisms/layout/HeaderWrapper";
import { ErrorBoundary } from "@/components/molecules/presentation/ErrorBoundary";
import { SanityConfigDebug } from "@/components/debug/SanityConfigDebug";

import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDraftMode = (await draftMode()).isEnabled;

  return (
    <ErrorBoundary>
      <HeaderWrapper />
      {children}
      <SanityLive />
      {isDraftMode && (
        <>
          <VisualEditing />
          <DisableDraftMode />
        </>
      )}
      <SanityConfigDebug />
    </ErrorBoundary>
  );
}
